<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLBkrYpc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLBkrYpc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLBkrYpc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLBkrYpc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLBkrYpc\App_KernelDevDebugContainer([
    'container.build_hash' => 'LBkrYpc',
    'container.build_id' => '96bd8f3d',
    'container.build_time' => 1629353575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLBkrYpc');
